/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "panoply.h"
panoply * database;
void *
init_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;


	database=malloc(sizeof(panoply));

	/*init abonnements*/
	printf("Initialisation des abonnements\n");
    database->abonnements.nb_different_abonnement=4;
        /* ~Abonnement n°1~ */
		printf("Abo 1\n");
        database->abonnements.abonnements[0].id_abo = 0;
        strcpy(database->abonnements.abonnements[0].type_abo,"Un peu");
        database->abonnements.abonnements[0].prix_abo=69;
        database->abonnements.abonnements[0].credit_abo=1;

        /* ~Abonnement n°2~ */
		printf("Abo 2\n");
        database->abonnements.abonnements[1].id_abo = 1;
        strcpy(database->abonnements.abonnements[1].type_abo,"Beaucoup");
        database->abonnements.abonnements[1].prix_abo=159;
        database->abonnements.abonnements[1].credit_abo=3;

        /* ~Abonnement n°3~ */
		printf("Abo 3\n");
        database->abonnements.abonnements[2].id_abo = 2;
        strcpy(database->abonnements.abonnements[2].type_abo,"Passionnément");
        database->abonnements.abonnements[2].prix_abo=229;
        database->abonnements.abonnements[2].credit_abo=5;

        /* ~Abonnement n°4~ */
		printf("Abo 4\n");
        database->abonnements.abonnements[3].id_abo = 3;
        strcpy(database->abonnements.abonnements[3].type_abo,"A la folie");
        database->abonnements.abonnements[3].prix_abo=319;
        database->abonnements.abonnements[3].credit_abo=8;    
    
    /*init collections*/
    database->collections.nb_different_collection=2;
    
        /* ~Collection n°1~ */
        database->collections.collection[0].id_collection=0;
        strcpy(database->collections.collection[0].nom_collection,"Robes longues");

        /* ~Collection n°2~ */
        database->collections.collection[1].id_collection=1;
        strcpy(database->collections.collection[1].nom_collection,"Robes mini");

    /*init marques*/
    database->marques.nb_different_brand=2;

        /* ~Marques n°1~ */
        database->marques.brands[0].id_brand=0;
        strcpy(database->marques.brands[0].brand_name,"3.1 Phillip Lim");
        strcpy(database->marques.brands[0].description,"Un style classique maitrisé associé à une touche sportwear définit l'identité de la maison 3.1 Phillip Lim.\n\nLe minimalisme des pièces et la palette de couleurs restreinte focalisent l'attention sur des coupes structurées et des détails originaux mis en valeur par des matières nobles et texturées pour une femme libre et naturellement chic.");

        /* ~Marques n°2~ */
        database->marques.brands[1].id_brand=1;
        strcpy(database->marques.brands[1].brand_name,"Alexis Mabille");
        strcpy(database->marques.brands[1].description,"Formé aux côtés de Hedi Slimane chez Dior, Alexis Mabille s'intéresse particulièrement à l'androgynie et aux frontières du masculin et du féminin. Il lance sa griffe en 2005 et crée des collections unisexes remarquées du milieu de la mode. Il revisite le nœud papillon en jouant sur les volumes et cet accessoire désuet devient sa marque de fabrique.");

    /*init articles*/
    database->articles.nb_different_article=5;
   
       /* ~Article n°1~ */
       database->articles.article[0].id_article = 0; 
       strcpy(database->articles.article[0].nom,"Flower dress");
       database->articles.article[0].taille[0]=34;
       database->articles.article[0].taille[1]=38;
       database->articles.article[0].taille[2]=42;
       database->articles.article[0].taille[3]=-1;        
       database->articles.article[0].pt_livraison=1;
       database->articles.article[0].prix_location=55;       
       database->articles.article[0].collection_reference=database->collections.collection[0];                   
       database->articles.article[0].brand_reference = database->marques.brands[1];
       database->articles.article[0].credit=1;
       database->articles.article[0].stock=5;

    /*init comptes*/
    database->comptes.nbCompte=1;

        /* ~compte n°1~ */
        database->comptes.cmpt[0].id_compte=0;
        strcpy(database->comptes.cmpt[0].email.email,"client1@univ-brest.fr"); 
        strcpy(database->comptes.cmpt[0].mdp.mdp,"client1"); 
        strcpy(database->comptes.cmpt[0].nom,"masse");
        strcpy(database->comptes.cmpt[0].prenom,"damien");
        database->comptes.cmpt[0].date_de_naissance.jour = 2;
        database->comptes.cmpt[0].date_de_naissance.mois = 5;
        database->comptes.cmpt[0].date_de_naissance.annee = 1975;
        database->comptes.cmpt[0].telephone = 655482746;
        strcpy(database->comptes.cmpt[0].profession,"maitre de conf");
        strcpy(database->comptes.cmpt[0].pays,"france");
        database->comptes.cmpt[0].nb_credit=7;
        database->comptes.cmpt[0].connaissance = 1;
        database->comptes.cmpt[0].abonnement_suivi = database->abonnements.abonnements[0];


    /*init commandes*/
    database->commandes.nbCommande=0;
	printf("Fin de l'initialisation\n");

	return (void *) &result;
}

compte *
create_account_1_svc(compte *argp, struct svc_req *rqstp)
{
	static compte  result;

	printf("Création de compte\n");
	database->comptes.cmpt[database->comptes.nbCompte]=*argp;
	database->comptes.cmpt[database->comptes.nbCompte].id_compte=database->comptes.nbCompte;
	result=database->comptes.cmpt[database->comptes.nbCompte];
	database->comptes.nbCompte++;
	printf("Fin création de compte\n");

	return &result;
}

int *
log_in_1_svc(identifiants *argp, struct svc_req *rqstp)
{
	static int  result;

	result=-1;
	printf("Connexion\n");
	printf("nombre de comptes : %d\n",database->comptes.nbCompte);
	for (int i =0;i<database->comptes.nbCompte;i++){
		if (strcmp(database->comptes.cmpt[i].email.email,argp->email.email)==0 && strcmp(database->comptes.cmpt[i].mdp.mdp,argp->mdp.mdp)==0){
			result=i;
			printf("Connexion réussie\n");
		}
	}
	if (result==-1){
		printf("Connexion raté\n");
	}
	
	printf("id retour %d\n",result);

	return &result;
}

list_abonnement *
list_type_abo_1_svc(void *argp, struct svc_req *rqstp)
{
	printf("Envoie des listes d'abonnement\n");
	static list_abonnement  result;
	if (database == (panoply *)NULL){
		printf("Ta database n'est pas initialisée");
	}
	result=database->abonnements;

	return &result;
}

compte *
affecter_abo_client_1_svc(compte *argp, struct svc_req *rqstp)
{
	static compte  result;

	printf("Ajout de l'abonnement");
	//ajout de l'abonnement
	int id_user = argp->id_compte;
	int choix_abonnement=argp->abonnement_suivi.id_abo;
	database->comptes.cmpt[id_user].abonnement_suivi=database->abonnements.abonnements[choix_abonnement];
	printf("Abonnement affecté : %s \n",database->comptes.cmpt[id_user].abonnement_suivi.type_abo);
	//update du nombre de credit
	printf("Mise à jour de la base de donnee\n");
	int credit_abo = database->comptes.cmpt[id_user].abonnement_suivi.credit_abo;
	int credit_restant=database->comptes.cmpt[id_user].nb_credit;
	database->comptes.cmpt[id_user].nb_credit = credit_restant + credit_abo;
	printf("Fin de l'ajout de l'abonnement\n");
	result=database->comptes.cmpt[id_user];

	return &result;
}

list_collection *
list_all_collection_1_svc(void *argp, struct svc_req *rqstp)
{
	static list_collection  result;

    printf("Liste les collections\n");
	printf("Nombre de collections %d\n",database->collections.nb_different_collection);
	result=database->collections;
    printf("Fin liste collection\n");
	return &result;
}

article_list *
list_all_collection_clothes_1_svc(collection *argp, struct svc_req *rqstp)
{
	static article_list  result;

	result.nb_different_article=0;

	int id_collection=argp->id_collection;
	for (int i =0 ; i<database->articles.nb_different_article ; i++){
		if( database->articles.article[i].collection_reference.id_collection == id_collection ){
			result.article[result.nb_different_article]=database->articles.article[i];
			result.nb_different_article++;
		}
	}

	return &result;
}

cart *
add_to_cart_1_svc(cart *argp, struct svc_req *rqstp)
{
	static cart  result;

	int id_commande=argp->id_cart;
	database->commandes.listCommande[id_commande]=*argp;
	database->commandes.nbCommande++;

	result = *argp;
	free(database);

	return &result;
}
