/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "panoply.h"

void
service_panoply_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char *init_1_arg;
	compte  *result_2;
	compte  create_account_1_arg;
	int  *result_3;
	identifiants  log_in_1_arg;
	list_abonnement  *result_4;
	char *list_type_abo_1_arg;
	compte  *result_5;
	compte  affecter_abo_client_1_arg;
	list_collection  *result_6;
	char *list_all_collection_1_arg;
	article_list  *result_7;
	collection  list_all_collection_clothes_1_arg;
	cart  *result_8;
	cart  panier;

#ifndef	DEBUG
	clnt = clnt_create (host, SERVICE_PANOPLY, SERVICE_VERSION_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("---------------------------------------------------\n");

	printf("Initialisation base de donnee\n");
	result_1 = init_1((void*)&init_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("Fin initialization de la base de donnee\n");

	printf("---------------------------------------------------\n");

	printf("Création de compte\n");
	printf("e mail : tomkimsour@hotmail.fr\n");
	strcpy(create_account_1_arg.email.email,"tomkimsour@hotmail.fr");
	printf("mot de passe : tom\n");
	strcpy(create_account_1_arg.mdp.mdp,"tom");
	printf("nom : philippe\n");
	strcpy(create_account_1_arg.nom,"philippe");
	printf("prenom : andre\n");
	strcpy(create_account_1_arg.prenom,"andre");
	printf("Date de naissance 03/03/1998 \n");
	create_account_1_arg.date_de_naissance.jour=3;
	create_account_1_arg.date_de_naissance.mois=3;
	create_account_1_arg.date_de_naissance.annee=1998;
	printf("numero de telephone : 2596543\n");
	create_account_1_arg.telephone=2596543;
	printf("profession : etudiant\n");
	strcpy(create_account_1_arg.profession,"etudiant");
	printf("pays : france\n");
	strcpy(create_account_1_arg.pays,"france");
    create_account_1_arg.nb_credit=0;	
	printf("conu - Une_recherche_en_ligne\n");
	create_account_1_arg.connaissance=2;

	result_2 = create_account_1(&create_account_1_arg, clnt);
	if (result_2 == (compte *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Fin création compte\n");

	printf("---------------------------------------------------\n");


	printf("Connexion\n");
	printf("Adresse mail : tomkimsour@hotmail.fr\n");
	strcpy(log_in_1_arg.email.email,"tomkimsour@hotmail.fr");
	printf("Mot de passe : tom\n");
	strcpy(log_in_1_arg.mdp.mdp,"tom");	
	result_3 = log_in_1(&log_in_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Fin connexion\n");

	printf("---------------------------------------------------\n");

	printf("Liste abonnnement\n");
	result_4 = list_type_abo_1((void*)&list_type_abo_1_arg, clnt);
	if (result_4 == (list_abonnement *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	for (int i=0;i<result_4->nb_different_abonnement;i++){
		printf("Abonnement n°%d : %s, prix : %d, credit par mois : %d\n",result_4->abonnements[i].id_abo,result_4->abonnements[i].type_abo,result_4->abonnements[i].prix_abo,result_4->abonnements[i].credit_abo);
	}
	printf("Fin liste abonnement\n");

	printf("---------------------------------------------------\n");

	int id_abonnement;
	printf("Abonnement choisi : 2\n");
	result_2->abonnement_suivi=result_4->abonnements[1];

	result_5 = affecter_abo_client_1(result_2, clnt);
	if (result_5 == (compte *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Fin ajout abonnement\n");

	printf("---------------------------------------------------\n");

	printf("Affichage de toutes les collections\n");
	result_6 = list_all_collection_1((void*)&list_all_collection_1_arg, clnt);
	if (result_6 == (list_collection *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	for (int i=0;i<result_6->nb_different_collection;i++){
		printf("%d - %s\n",result_6->collection[i].id_collection,result_6->collection[i].nom_collection);
	}
	printf("Fin d'affichage des collections \n");

	printf("---------------------------------------------------\n");

	printf("Identifiant d'une collection à parcourir : 0 \n");
	list_all_collection_clothes_1_arg.id_collection=0;
	result_7 = list_all_collection_clothes_1(&list_all_collection_clothes_1_arg, clnt);
	if (result_7 == (article_list *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	for (int i=0;i<result_7->nb_different_article;i++){
		printf("Article %d : %s		| Jetons : %d| Euros : %d\n",result_7->article[i].id_article,result_7->article[i].nom,result_7->article[i].credit,result_7->article[i].prix_location);
	}
	printf("Fin affichage des articles associé à la collection choisie\n");

	printf("---------------------------------------------------\n");

	printf("Veuillez choisir l'id de l'article à ajouter au panier\n");
	printf("Ajout de l'article d'identifiant 0\n");
	panier.id_cart=*result_3;
	panier.nbArticle=1;
	panier.list_article[0]=result_7->article[0];
	result_8 = add_to_cart_1(&panier, clnt);
	if (result_8 == (cart *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	panier=*result_8;
	printf("Fin ajout\n");
	printf("---------------------------------------------------\n");

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	service_panoply_1 (host);
exit (0);
}
