/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "panoply.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
service_panoply_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		compte create_account_1_arg;
		identifiants log_in_1_arg;
		article add_cloth_to_collection_1_arg;
		article remove_cloth_to_collection_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case INIT:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) init_1_svc;
		break;

	case CREATE_ACCOUNT:
		_xdr_argument = (xdrproc_t) xdr_compte;
		_xdr_result = (xdrproc_t) xdr_compte;
		local = (char *(*)(char *, struct svc_req *)) create_account_1_svc;
		break;

	case LOG_IN:
		_xdr_argument = (xdrproc_t) xdr_identifiants;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) log_in_1_svc;
		break;

	case LIST_ALL_COLLECTION:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_list_collection;
		local = (char *(*)(char *, struct svc_req *)) list_all_collection_1_svc;
		break;

	case ADD_CLOTH_TO_COLLECTION:
		_xdr_argument = (xdrproc_t) xdr_article;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) add_cloth_to_collection_1_svc;
		break;

	case REMOVE_CLOTH_TO_COLLECTION:
		_xdr_argument = (xdrproc_t) xdr_article;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) remove_cloth_to_collection_1_svc;
		break;

	case DISPLAY_ABONNEMENT:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_list_account;
		local = (char *(*)(char *, struct svc_req *)) display_abonnement_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (SERVICE_PANOPLY, SERVICE_VERSION_2);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, SERVICE_PANOPLY, SERVICE_VERSION_2, service_panoply_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SERVICE_PANOPLY, SERVICE_VERSION_2, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, SERVICE_PANOPLY, SERVICE_VERSION_2, service_panoply_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SERVICE_PANOPLY, SERVICE_VERSION_2, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
