/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "panoply.h"


void
service_panoply_1(char *host)
{
	CLIENT *clnt;
	void  *result_1;
	char *init_1_arg;
	compte  *result_2;
	compte  create_account_1_arg;
	int  *result_3;
	identifiants  log_in_1_arg;
	list_collection  *result_4;
	char *list_all_collection_1_arg = NULL;
	void  *result_5;
	article  new_cloth;
	void  *result_6;
	article  remove_cloth_to_collection_1_arg;
	list_account  *result_7;
	char *display_abonnement_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SERVICE_PANOPLY, SERVICE_VERSION_2, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("---------------------------------------------------\n");

	printf("Initialisation base de donnee\n");
	result_1 = init_1((void*)&init_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
		return;
	}

	printf("Fin initialization de la base de donnee\n");

	printf("---------------------------------------------------\n");

	printf("Création de compte\n");
	printf("e mail : tomkimsour@hotmail.fr\n");
	strcpy(create_account_1_arg.email.email,"tomkimsour@hotmail.fr");
	printf("mot de passe : tom\n");
	strcpy(create_account_1_arg.mdp.mdp,"tom");
	printf("nom : philippe\n");
	strcpy(create_account_1_arg.nom,"philippe");
	printf("prenom : andre\n");
	strcpy(create_account_1_arg.prenom,"andre");
	printf("Date de naissance 03/03/1998 \n");
	create_account_1_arg.date_de_naissance.jour=3;
	create_account_1_arg.date_de_naissance.mois=3;
	create_account_1_arg.date_de_naissance.annee=1998;
	printf("numero de telephone : 2596543\n");
	create_account_1_arg.telephone=2596543;
	printf("profession : etudiant\n");
	strcpy(create_account_1_arg.profession,"etudiant");
	printf("pays : france\n");
	strcpy(create_account_1_arg.pays,"france");
    create_account_1_arg.nb_credit=0;	
	printf("conu - Une_recherche_en_ligne\n");

	create_account_1_arg.connaissance=2;

	create_account_1_arg.abonnement_suivi.id_abo =0;
	memset(create_account_1_arg.abonnement_suivi.type_abo, '\0', 30);
	create_account_1_arg.abonnement_suivi.prix_abo=0;
	create_account_1_arg.abonnement_suivi.credit_abo=0;
	create_account_1_arg.date_abonnement.jour = 0;
	create_account_1_arg.date_abonnement.mois = 0;
	create_account_1_arg.date_abonnement.annee = 0;
	

	result_2 = create_account_1(&create_account_1_arg, clnt);
	if (result_2 == (compte *) NULL) {
		clnt_perror (clnt, "call failed");
		return;
	}
	printf("Fin création compte\n");

	printf("---------------------------------------------------\n");


	printf("Connexion\n");
	printf("adresse mail : tomkimsour@hotmail.fr\n");
	strcpy(log_in_1_arg.email.email,"tomkimsour@hotmail.fr");
	printf("mot de passe : tom\n");
	strcpy(log_in_1_arg.mdp.mdp,"tom");	
	result_3 = log_in_1(&log_in_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
		return;
	}
	printf("id utilisateur : %d\n", *result_3);
	printf("Fin connexion\n");

	printf("---------------------------------------------------\n");

	printf("Affichage de toutes les collections\n");
	result_4 = list_all_collection_1((void*)&list_all_collection_1_arg, clnt);
	if (result_4 == (list_collection *) NULL) {
		clnt_perror (clnt, "call failed");
		return;
	}
	for (int i=0;i<result_4->nb_different_collection;i++){
		printf("%d - %s\n",result_4->collection[i].id_collection,result_4->collection[i].nom_collection);
	}
	printf("Fin d'affichage des collections \n");

	printf("---------------------------------------------------\n");
	
	printf("Ajout d'un article à la collection Robes mini\n");
	new_cloth.id_article=2;
	strcpy(new_cloth.nom,"Black dress");
	new_cloth.taille[0]=34;
	new_cloth.taille[1]=38;
	new_cloth.taille[2]=42;
	new_cloth.taille[3]=-1;        
	new_cloth.pt_livraison=1;
	new_cloth.prix_location=62;       
	new_cloth.collection_reference.id_collection=1;                   
	new_cloth.brand_reference.id_brand=1;
	new_cloth.credit=1;
	new_cloth.stock=15;
	result_5 = add_cloth_to_collection_1(&new_cloth, clnt);
	if (result_5 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
		return;
	}
	printf("ajout termine \n");

	printf("---------------------------------------------------\n");

	printf("Enlevement du dernier article de la bdd \n");
	result_6 = remove_cloth_to_collection_1(&new_cloth, clnt);
	if (result_6 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
		return;
	}
	printf("Enlevement du dernier article de la bdd termine\n");

	printf("---------------------------------------------------\n");

	printf("Affichage des abonnements de tous les comptes \n");
	result_7 = display_abonnement_1((void*)&display_abonnement_1_arg, clnt);
	if (result_7 == (list_account *) NULL) {
		clnt_perror (clnt, "call failed");
		return;
	}
	for (int i=0 ; i<result_7->nbCompte;i++){
		printf("Compte n°%d : %s\n",result_7->cmpt[i].id_compte+1,result_7->cmpt[i].abonnement_suivi.type_abo);
	}
	printf("Fin de l'abonnement \n");

	printf("---------------------------------------------------\n");

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	service_panoply_1 (host);
exit (0);
}
